### ISSUE TITLE
How to run your project? 

### ISSUE THREAD

**Issue by rohan23chhabra** [ankitesh97/Gesture-Recognition-CNN#1]
When I run it using `python cnn_predict.py` it gives me error:

`No such file or directory: 'pickle_models/cnn_object_15_'
`

I am using python2.7

**Comment by ankitesh97** [comment]
Hi,
You will have to first train the model using cnn_model.py

**Comment by Sachihiro** [comment]
Do i need to train my model before I can use it?. I can't run it

**Comment by ankitesh97** [comment]
Hi,
Yes you will have to train your model. I will attach the model that I had trained.

**Comment by Sachihiro** [comment]
Thank you very much. I appreciate your reply :)

**Comment by AkramAshrafRamses** [comment]
when i run cnn_model.py , i got this
AttributeError: 'NoneType' object has no attribute 'X_train'

can you please help my by specifying what files to run first cuz iam new to machine learning
thanks in advance
